spring:
  datasource:
    #url: jdbc:mysql://localhost:3308/xyz_hotel?createDatabaseIfNotExist=true
    #password: mysqlshehan99$$
    #username: root

    url: jdbc:mysql://localhost:3306/xyz_hotel?createDatabaseIfNotExist=true
    password:
    username: root

    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  mvc:
    view:
      #prefix: /WEB-INF/
      suffix: .jsp

